---
kind: golang.Generate
spec:
  experimentalFlags:
    - --experimental_allow_proto3_optional
  vtProtobufEnabled: true
  specs:
    - source: https://raw.githubusercontent.com/cosi-project/specification/5c734257bfa6a3acb01417809797dbfbe0e73c71/proto/v1alpha1/resource.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/5c734257bfa6a3acb01417809797dbfbe0e73c71/proto/v1alpha1/state.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/5c734257bfa6a3acb01417809797dbfbe0e73c71/proto/v1alpha1/meta.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: api/key_storage/key_storage.proto
      subdirectory: key_storage/
      genGateway: false
      external: false
---
kind: golang.UnitTests
spec:
  extraArgs: "-p 1" # limit parallelism to avoid flakiness on busy GH runners
---
kind: auto.CI
spec:
  provider: drone
---
kind: service.CodeCov
spec:
  targetThreshold: 45
