---
kind: golang.Generate
spec:
  experimentalFlags:
    - --experimental_allow_proto3_optional
  vtProtobufEnabled: true
  specs:
    - source: https://raw.githubusercontent.com/smira/specification/fd31e32e8060fec72a4f9ee7f3b7d1924ea3e4d0/proto/v1alpha1/resource.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/smira/specification/fd31e32e8060fec72a4f9ee7f3b7d1924ea3e4d0/proto/v1alpha1/state.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/smira/specification/fd31e32e8060fec72a4f9ee7f3b7d1924ea3e4d0/proto/v1alpha1/runtime.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/smira/specification/fd31e32e8060fec72a4f9ee7f3b7d1924ea3e4d0/proto/v1alpha1/meta.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
