---
kind: golang.Generate
spec:
  experimentalFlags:
    - --experimental_allow_proto3_optional
  vtProtobufEnabled: true
  specs:
    - source: https://raw.githubusercontent.com/cosi-project/specification/aec70d02f588efc9463b85e551057313c9754dda/proto/v1alpha1/resource.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/aec70d02f588efc9463b85e551057313c9754dda/proto/v1alpha1/state.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/aec70d02f588efc9463b85e551057313c9754dda/proto/v1alpha1/runtime.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/aec70d02f588efc9463b85e551057313c9754dda/proto/v1alpha1/meta.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: api/key_storage/key_storage.proto
      subdirectory: key_storage/
      genGateway: false
      external: false
